---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
    linux-armv7:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
